# -*- coding: utf-8 -*-
"""
Created on Thu Sep 19 15:23:47 2019

#Calculate the length of amplicons.fasta generated by PrimerProspector.
#1st Step: Run taxaID.py to get the taxa.csv
#2nd Step: Run Amplicon-Analysis.py and get the final result

#Usage:
    Python Amplicon-Analysis.py amplicons.fasta taxa.csv

#Input file:
    amplicons.fasta: The amplicons.fasta generated by PrimerProspector.
    taxa.csv: taxa flie generated by taxaID.py
#Output file: 
    amplicons.fasta.png & amplicons.fasta.pdf: Histogram of length distribution
    Output.txt: The statistics of amplicons.fasta
    amplicons.file.csv: the csv file sorted by length and contain taxa info
    


@author: Junyu


"""
#import numpy as np
import sys
import pylab
import numpy as np
import pandas as pd
from Bio import SeqIO
file = sys.argv[1]
taxa = sys.argv[2]
print(file)
print(taxa)

sizes = [len(rec) for rec in SeqIO.parse(file , "fasta")]
#%pylab inline
#%matplotlib inline
pylab.hist(sizes, bins=20)
pylab.title("%i sequences\nLengths %i to %i" \
            % (len(sizes),min(sizes),max(sizes)))
pylab.xlabel("Sequence length (bp)")
pylab.ylabel("Count")
#pylab.show()

pylab.savefig(file+"_len_stat.png")
pylab.savefig(file+"_len_stat.pdf")

mean = sum(sizes)/len(sizes)
#lenrange = max(sizes)-min(sizes)
percent = np.percentile(sizes, [10, 20, 30, 40, 50, 60, 70, 80, 90,])

sta= open(file+"_len_stat.txt","w")
sta.write("10% is: "+ str(percent[0]) +"\n" \
          "20% is: "+ str(percent[1]) +"\n" \
          "30% is: "+ str(percent[2]) +"\n" \
          "40% is: "+ str(percent[3]) +"\n" \
          "50% is: "+ str(percent[4]) +"\n" \
          "60% is: "+ str(percent[5]) +"\n" \
          "70% is: "+ str(percent[6]) +"\n" \
          "80% is: "+ str(percent[7]) +"\n" \
          "90% is: "+ str(percent[8]) +"\n\n" \
          
          
          "Min length is:" + str(min(sizes))+"\n" \
          "mean is: "+ str(mean) +"\n" \
          "Max length is:" + str(max(sizes))+"\n" \
        
          )
sta.close() 

#import taxa as dataframe
taxa = pd.read_csv(taxa)


f = pd.DataFrame()
seqdict = {}
for seq_record in SeqIO.parse(file, "fasta"):
    f = f.append({'ID':seq_record.id, "Len":len(seq_record)}, ignore_index=True)

#add taxaID in
merge = pd.merge(f, taxa, on='ID', how='left')

sort_by_len = merge.sort_values('Len')
cols_to_keep = ['Len', 'taxa']
#print(sort_by_len.head(n=3))
sort_by_len.to_csv(file +"_len_stat.csv", encoding = "utf-8")
#sort_by_len[cols_to_keep].to_csv(file +".csv", encoding = "utf-8")

